### ISSUE TITLE
PCardList method from_file Error "self.read_cards_from_str() does not exist"

### ISSUE THREAD

**Issue by turbam** [EskoSalaka/mtgtools#1]
Hi,
I just installed mtgtools version 0.9 with PIP and the error above appears when I try to load a deck from a .txt file generated with cockatrice.

In line 1286 of the PCardList.py file there is the following code:

` return self.read_cards_from_str(f.read())`

I changed it to 

`return self.from_str(f.read())`

and that seems to get it working.

Thanks for creating this!

Kind regards,
Konstantin

**Comment by EskoSalaka** [comment]
Hi Konstantin!

I must say that its great to see someone discovering these tools, and even nicer to see someone using them for something useful!

Thank you for the report! At the moment Im very busy, but I am certainly planning to fix this plus a few other bugs ive discovered in the following few months!

**Comment by gus3000** [comment]
Hi !
I stumbled upon this exact bug !
I use your tools a lot, so it's only fair I start contributing a bit.
I have a lot more changes prepared, but I figured I'd start with a simple bug :)
