### ISSUE TITLE
mtgdb.scryfall_update() fails

### ISSUE THREAD

**Issue by pavel-rybnicek** [EskoSalaka/mtgtools#10]
Method mtgdb.scryfall_update() fails with error in method process_card_page_response:
    PCard(card_json) for card_json in response[data_identifier]
KeyError: 'data'

The problem is with set "mir", for example.
In method process_scryfall_cards the URIs of pages are generated. The set says it has **351** cards in it, which leads to 3 URIs:
[
'https://api.scryfall.com/cards/search?include_extras=true&order=set&page=1&q=e%3Amir&unique=prints', 
'https://api.scryfall.com/cards/search?include_extras=true&order=set&page=2&q=e%3Amir&unique=prints', 
'https://api.scryfall.com/cards/search?include_extras=true&order=set&page=3&q=e%3Amir&unique=prints']
The first URI says there is **335** cards in total (and has_more is true)
The second says there is **350** cards in total and has_more is **false**
The lastone says there is no such page and thus the resulting json doesn't contain any "data" key. ("You have paginated beyond the end of these results")

**Comment by pavel-rybnicek** [comment]
Sorry, the first paragraph is incorrect. Correct version:
  File "mtgtools/util/api_requests.py", line 36, in process_card_page_response
    card_page_uri, headers)[data_identifier]
KeyError: 'data'

**Comment by EskoSalaka** [comment]
Hi pavel. I think i had these kinds of errors before too because scryfall
has sometimes marked false card counts for certain sets. I cant confirm
this atm, but you could notify scryfall if their api indeed shows an
incorrect card count. I thought i fixed the code to handle such errors but
i guess its not working...

In any case, im quite busy atm, i might have time to look into it next week!

**Comment by Julian-Brendel** [comment]
Hey, just about to write a project with this library and am facing the same problem.
Happy to look into it and create a PR

**Comment by EskoSalaka** [comment]
Really cool to hear that! The bug is prob quite simple to fix, one just
needs to add a some sort of check that the 'next' pagination actually
exists. On another note, im guessing scryfall has some automation that
sometimes mislabels the set card counts. I remember they had like a bunch
of sets of 350 cards marked as having 351 cards instead

**Comment by Julian-Brendel** [comment]
Can confirm that problematic sets are `ody` and `mir`,  both labelled incorrectly, containing 351 instead of 350 cards.
Created PR fixing the KeyError exception, skipping pages with pagination error.
https://github.com/EskoSalaka/mtgtools/pull/11

**Comment by Julian-Brendel** [comment]
Looking further into this, identified all the sets that have mislabeled card-counts
```python
[(1, Ikoria: Lair of Behemoths(iko)),
 (1, Core Set 2020(m20)),
 (3, Aether Revolt(aer)),
 (4, Kaladesh(kld)),
 (1, Shadows over Innistrad Promos(psoi)),
 (5, Shadows over Innistrad(soi)),
 (2, Happy Holidays(hho)),
 (2, Odyssey(ody)),
 (1, Arena League 1999(pal99)),
 (1, Prerelease Events(ppre)),
 (7, Portal(por)),
 (5, Fifth Edition(5ed)),
 (1, Mirage(mir)),
 (1, Fourth Edition(4ed)),
 (3, The Dark(drk)),
 (1, Antiquities(atq)),
 (14, Arabian Nights(arn))]
```

At the moment, whenever running `scryfall_update()`, the database always fetches all sets, resulting in ~750 requests being made. Made be worth to speed this up by only fetching set's where card_count doesn't match up with cards already in database.

**Comment by Julian-Brendel** [comment]
@EskoSalaka have a look in #12, regarding filtering for incomplete set's before updating.

**Comment by EskoSalaka** [comment]
Its really cool to see that people are actually coming to help! But atm im
reluctant to accept any pull request without checking first because ill be
drunk for the next few days :D even if the checks are in place, its
generally bad if the sets api gives a false card_count

**Comment by pavel-rybnicek** [comment]
Well, just came from a party, so I can understand. :-) Anyway, I made a local quick fix to ignore invalid URIs. Faced another problem immediatelly - cannot commit and close database with error:

  File "/home/pryb/miniconda3/envs/fastai7/lib/python3.6/site-packages/ZODB/Connection.py", line 283, in close
    raise ConnectionStateError("Cannot close a connection joined to "
ZODB.POSException.ConnectionStateError: Cannot close a connection joined to a transaction

**Comment by pavel-rybnicek** [comment]
Well, just a note - when I search for "set:mir" at scryfall, I get a result of 351 cards. 350 is in "boosters", 1 extra is in something called "variations". I guess this can explain the differencies.
(I have actually no idea what's "booster" or a "variation", I'm not into MTG that much. I just build the sorting machines. :) )

**Comment by pavel-rybnicek** [comment]
I've made a similar fix myself. Now even with a freshly updated database I get:
Found a total of 0 new sets and 47 new cards
