### ISSUE TITLE
Read-Only Configuration

### ISSUE THREAD

**Issue by FishyF1sh** [EskoSalaka/mtgtools#23]
Hi

Thank you very much for this awesome tool!!

I want to use the underlying DB from multiple (read-only) processes. Could we add `read_only: bool = False` as an argument to `MtgDB.__init__`, and forward it to `ZODB.FileStorage.FileStorage` from the constructor? Or is my use case too niche?

**Comment by EskoSalaka** [comment]
Hi!

I think this is a pretty reasonable feature. Ill get back on this in a bit, or you could even do a pull request if you have some code ready :)

**Comment by EskoSalaka** [comment]
Hey, I have now included all the ZODB.FileStorage.FileStorage options to the DB, so you can now start it with the read_only=True flag :)
